dist: trusty
sudo: false
language: node_js
node_js:
  - '10'
addons:
  chrome: stable
cache:
  directories:
    - ./node_modules
install:
  - npm install
  - npm install -g firebase-tools
script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - ng build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
